# Generates gl/ffx_fsr2_glsl_embedded.h: the GLSL sources of all FSR2 passes plus
# every header they transitively include, embedded as string constants, with the
# native-GL compatibility transforms pre-applied. The GL backend compiles these
# through the driver's GLSL front end on NVIDIA, where the glShaderBinary SPIR-V
# path generates ~3x slower code (see ffx_fsr2_gl.cpp). Rerun after editing any
# file under src/ffx-fsr2-api/shaders and check in the result.
import os, re, io

SRC = os.path.join(os.path.dirname(os.path.abspath(__file__)), "src", "ffx-fsr2-api", "shaders")
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "src", "ffx-fsr2-api", "gl", "ffx_fsr2_glsl_embedded.h")

ROOTS = [
    "ffx_fsr2_depth_clip_pass.glsl2",
    "ffx_fsr2_reconstruct_previous_depth_pass.glsl2",
    "ffx_fsr2_lock_pass.glsl2",
    "ffx_fsr2_accumulate_pass.glsl2",
    "ffx_fsr2_rcas_pass.glsl2",
    "ffx_fsr2_compute_luminance_pyramid_pass.glsl2",
    "ffx_fsr2_autogen_reactive_pass.glsl2",
    "ffx_fsr2_tcr_autogen_pass.glsl2",
]

def transform(text):
    # The include directive extension is unneeded (the backend expands includes) and
    # the image_load_formatted one is Vulkan-only; native GL allows a writeonly image
    # without a format qualifier, which is the only formatless declaration.
    text = re.sub(r"#extension GL_GOOGLE_include_directive[^\n]*", "", text)
    text = re.sub(r"#extension GL_EXT_shader_image_load_formatted[^\n]*", "", text)
    # NVIDIA requires #extension before any code; the SPD header emits subgroup
    # extensions mid-file. All subgroup extensions are declared in the runtime
    # prelude instead.
    text = re.sub(r"#extension GL_KHR_shader_subgroup[^\n]*", "", text)
    # A user function named like a builtin hides ALL builtin overloads in GLSL
    # (glslang is lenient about this, the NVIDIA front end is not), so the FFX
    # 3-parameter bitfield wrappers break their own calls to the wider builtins.
    # Substitute equivalent expressions.
    text = text.replace(
        "return bitfieldExtract(src, FfxInt32(off), FfxInt32(bits));",
        "return (src >> off) & ((1u << bits) - 1u);")
    text = text.replace(
        "return bitfieldInsert(src, ins, 0, FfxInt32(bits));",
        "return (ins & ((1u << bits) - 1u)) | (src & ~((1u << bits) - 1u));")
    return text

def includes_of(text):
    return re.findall(r'^[ \t]*#include[ \t]+"([^"]+)"', text, re.M)

files = {}
queue = list(ROOTS)
while queue:
    name = queue.pop()
    if name in files:
        continue
    path = os.path.join(SRC, name)
    if not os.path.exists(path):
        # Referenced only inside preprocessor-dead fp16 blocks.
        files[name] = None
        continue
    text = transform(io.open(path, encoding="utf-8").read())
    files[name] = text
    queue.extend(includes_of(text))

def cname(name):
    return "g_glsl_" + re.sub(r"[^A-Za-z0-9]", "_", name)

with io.open(OUT, "w", encoding="utf-8", newline="\n") as f:
    f.write("// Generated by generate_glsl_embedded.py - do not edit.\n")
    f.write("// GLSL sources for the native-GLSL pipeline path, includes unexpanded;\n")
    f.write("// the backend resolves them against this table.\n")
    f.write("#pragma once\n\n")
    total = 0
    for name in sorted(k for k, v in files.items() if v is not None):
        data = files[name].encode("utf-8")
        total += len(data)
        f.write("static const char %s[] = {" % cname(name))
        f.write(",".join(str(b) for b in data))
        f.write(",0};\n")
    f.write("\nstatic const struct { const char* name; const char* data; } g_glslEmbeddedFiles[] = {\n")
    for name in sorted(k for k, v in files.items() if v is not None):
        f.write('  { "%s", %s },\n' % (name, cname(name)))
    f.write("};\n")
print("embedded %d files, %d bytes of source -> %s" % (
    sum(1 for v in files.values() if v is not None), total, OUT))
missing = [k for k, v in files.items() if v is None]
if missing:
    print("skipped missing (fp16-only) includes:", ", ".join(sorted(missing)))
